/*
 * Port_Config.h
 *
 * Created: 5/12/2022 4:58:14 PM
 *  Author: Hany Hamza
 */ 


#ifndef PORT_CONFIG_H_
#define PORT_CONFIG_H_

//Configure pin directions. 0 for input, 1 for output.
#define PORTA_PIN0_DIR				0
#define PORTA_PIN1_DIR				0
#define PORTA_PIN2_DIR				0
#define PORTA_PIN3_DIR				0
#define PORTA_PIN4_DIR				0
#define PORTA_PIN5_DIR				0
#define PORTA_PIN6_DIR				0
#define PORTA_PIN7_DIR				0

#define PORTB_PIN0_DIR				0
#define PORTB_PIN1_DIR				0
#define PORTB_PIN2_DIR				0
#define PORTB_PIN3_DIR				0
#define PORTB_PIN4_DIR				0
#define PORTB_PIN5_DIR				0
#define PORTB_PIN6_DIR				0
#define PORTB_PIN7_DIR				0

#define PORTC_PIN0_DIR				0
#define PORTC_PIN1_DIR				0
#define PORTC_PIN2_DIR				0
#define PORTC_PIN3_DIR				0
#define PORTC_PIN4_DIR				0
#define PORTC_PIN5_DIR				0
#define PORTC_PIN6_DIR				0
#define PORTC_PIN7_DIR				0

#define PORTD_PIN0_DIR				0
#define PORTD_PIN1_DIR				0
#define PORTD_PIN2_DIR				0
#define PORTD_PIN3_DIR				0
#define PORTD_PIN4_DIR				0
#define PORTD_PIN5_DIR				0
#define PORTD_PIN6_DIR				0
#define PORTD_PIN7_DIR				0


/* Configure pins initial value
 * If input:	0 for floating, 1 for input pullup
 * If output:	0 for low, 1 for high
 */
#define PORTA_PIN0_INITIAL_VALUE	0
#define PORTA_PIN1_INITIAL_VALUE	0
#define PORTA_PIN2_INITIAL_VALUE	0
#define PORTA_PIN3_INITIAL_VALUE	0
#define PORTA_PIN4_INITIAL_VALUE	0
#define PORTA_PIN5_INITIAL_VALUE	0
#define PORTA_PIN6_INITIAL_VALUE	0
#define PORTA_PIN7_INITIAL_VALUE	0

#define PORTB_PIN0_INITIAL_VALUE	0
#define PORTB_PIN1_INITIAL_VALUE	0
#define PORTB_PIN2_INITIAL_VALUE	0
#define PORTB_PIN3_INITIAL_VALUE	0
#define PORTB_PIN4_INITIAL_VALUE	0
#define PORTB_PIN5_INITIAL_VALUE	0
#define PORTB_PIN6_INITIAL_VALUE	0
#define PORTB_PIN7_INITIAL_VALUE	0

#define PORTC_PIN0_INITIAL_VALUE	0
#define PORTC_PIN1_INITIAL_VALUE	0
#define PORTC_PIN2_INITIAL_VALUE	0
#define PORTC_PIN3_INITIAL_VALUE	0
#define PORTC_PIN4_INITIAL_VALUE	0
#define PORTC_PIN5_INITIAL_VALUE	0
#define PORTC_PIN6_INITIAL_VALUE	0
#define PORTC_PIN7_INITIAL_VALUE	0

#define PORTD_PIN0_INITIAL_VALUE	0
#define PORTD_PIN1_INITIAL_VALUE	0
#define PORTD_PIN2_INITIAL_VALUE	0
#define PORTD_PIN3_INITIAL_VALUE	0
#define PORTD_PIN4_INITIAL_VALUE	0
#define PORTD_PIN5_INITIAL_VALUE	0
#define PORTD_PIN6_INITIAL_VALUE	0
#define PORTD_PIN7_INITIAL_VALUE	0

#endif /* PORT_CONFIG_H_ */