/*
 * Port_Interface.h
 *
 * Created: 5/12/2022 4:58:06 PM
 *  Author: Hany Hamza
 */ 


#ifndef PORT_INTERFACE_H_
#define PORT_INTERFACE_H_

#include <stdlib.h>
#include "Port_Config.h"

//function to stringify a value
//the extra step allows the macros to expand before performing the stringification
#define STR_HELPER(x)				#x
#define STR(x)						STR_HELPER(x)

//concatenate the values for each pin of the DDR register
#define PORT_PORTA_DIR				STR(PORTA_PIN7_DIR) STR(PORTA_PIN6_DIR) STR(PORTA_PIN5_DIR) STR(PORTA_PIN4_DIR) STR(PORTA_PIN3_DIR) STR(PORTA_PIN2_DIR) STR(PORTA_PIN1_DIR) STR(PORTA_PIN0_DIR)
#define PORT_PORTB_DIR				STR(PORTB_PIN7_DIR) STR(PORTB_PIN6_DIR) STR(PORTB_PIN5_DIR) STR(PORTB_PIN4_DIR) STR(PORTB_PIN3_DIR) STR(PORTB_PIN2_DIR) STR(PORTB_PIN1_DIR) STR(PORTB_PIN0_DIR)
#define PORT_PORTC_DIR				STR(PORTC_PIN7_DIR) STR(PORTC_PIN6_DIR) STR(PORTC_PIN5_DIR) STR(PORTC_PIN4_DIR) STR(PORTC_PIN3_DIR) STR(PORTC_PIN2_DIR) STR(PORTC_PIN1_DIR) STR(PORTC_PIN0_DIR)
#define PORT_PORTD_DIR				STR(PORTD_PIN7_DIR) STR(PORTD_PIN6_DIR) STR(PORTD_PIN5_DIR) STR(PORTD_PIN4_DIR) STR(PORTD_PIN3_DIR) STR(PORTD_PIN2_DIR) STR(PORTD_PIN1_DIR) STR(PORTD_PIN0_DIR) 

//concatenate the values for each pin of the PORT register
#define PORT_PORTA_INITIAL_VALUES	STR(PORTA_PIN7_INITIAL_VALUE) STR(PORTA_PIN6_INITIAL_VALUE) STR(PORTA_PIN5_INITIAL_VALUE) STR(PORTA_PIN4_INITIAL_VALUE) STR(PORTA_PIN3_INITIAL_VALUE) STR(PORTA_PIN2_INITIAL_VALUE) STR(PORTA_PIN1_INITIAL_VALUE) STR(PORTA_PIN0_INITIAL_VALUE)
#define PORT_PORTB_INITIAL_VALUES	STR(PORTB_PIN7_INITIAL_VALUE) STR(PORTB_PIN6_INITIAL_VALUE) STR(PORTB_PIN5_INITIAL_VALUE) STR(PORTB_PIN4_INITIAL_VALUE) STR(PORTB_PIN3_INITIAL_VALUE) STR(PORTB_PIN2_INITIAL_VALUE) STR(PORTB_PIN1_INITIAL_VALUE) STR(PORTB_PIN0_INITIAL_VALUE)
#define PORT_PORTC_INITIAL_VALUES	STR(PORTC_PIN7_INITIAL_VALUE) STR(PORTC_PIN6_INITIAL_VALUE) STR(PORTC_PIN5_INITIAL_VALUE) STR(PORTC_PIN4_INITIAL_VALUE) STR(PORTC_PIN3_INITIAL_VALUE) STR(PORTC_PIN2_INITIAL_VALUE) STR(PORTC_PIN1_INITIAL_VALUE) STR(PORTC_PIN0_INITIAL_VALUE)
#define PORT_PORTD_INITIAL_VALUES	STR(PORTD_PIN7_INITIAL_VALUE) STR(PORTD_PIN6_INITIAL_VALUE) STR(PORTD_PIN5_INITIAL_VALUE) STR(PORTD_PIN4_INITIAL_VALUE) STR(PORTD_PIN3_INITIAL_VALUE) STR(PORTD_PIN2_INITIAL_VALUE) STR(PORTD_PIN1_INITIAL_VALUE) STR(PORTD_PIN0_INITIAL_VALUE)

void Port_void_init();

#endif /* PORT_INTERFACE_H_ */